
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// استخدام import.meta.env بدلاً من process.env
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://jtnqcyouncjoebqcalzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "SUPABASE_KEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// تحديد الموقع الحالي للتطبيق
const getLocalStorageKey = () => {
  // في بيئة الإنتاج، استخدم المجال الفعلي
  if (typeof window !== 'undefined' && window.location.hostname !== 'localhost') {
    return `sb-${SUPABASE_URL.replace(/^https?:\/\//, '').replace(/\/$/, '')}-auth-token`;
  }
  // في بيئة التطوير، استخدم مفتاح محدد
  return `sb-${SUPABASE_URL.replace(/^https?:\/\//, '').replace(/\/$/, '')}-auth-token-dev`;
};

// إنشاء عميل Supabase مع إعدادات محسنة للجلسة
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storageKey: getLocalStorageKey(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
});
